version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/kangaechu/richecker
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - run:
          name: run tests
          command: |
            go fmt ./...
            go vet ./...
            go test -v ./...
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
  deploy:
    docker:
      - image: circleci/golang:1.12
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/kangaechu/richecker
    steps:
      - checkout
      - run: go get -u github.com/mitchellh/gox
      - run: go get -u github.com/tcnksm/ghr
      - run: go mod download
      - run:
          name: cross compile
          command: |
            gox -osarch="linux/amd64 darwin/amd64" -output="dist/{{.Dir}}_{{.OS}}_{{.Arch}}" -verbose ./...
      - run:
          name: create release
          command: |
            ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME $CIRCLE_TAG  dist/

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/

